title = "gitleaks configuration"

[[rules]]
description = "Generic API Key"
regex = '''(?i)(api_key|apiKey|api-key|apikey|API_KEY)[\s=:]["']?[\w-]+["']?'''
tags = ["key", "api"]

[[rules]]
description = "AWS Access Key"
regex = '''(?i)(aws|amazon)?_?(access|secret)?_?key([^a-zA-Z0-9]+.{0,3})?([^a-zA-Z0-9\s]+)?(AKIA|ASIA|A3T|ACCA|AGPA|AIDA|AKPA|ANPA|AOCA|AOMA|APKA|APLA|AROA|ASIA|ATVA|AUMA|AXGA|AYDA|AZRA)[A-Z0-9]{16}'''
tags = ["key", "aws"]

[[rules]]
description = "AWS Secret Key"
regex = '''(?i)(aws|amazon)?_?(access|secret)?_?key([^a-zA-Z0-9]+.{0,3})?([^a-zA-Z0-9\s]+)?([A-Za-z0-9\/+=]{40})'''
tags = ["key", "aws"]

[[rules]]
description = "Generic Secret"
regex = '''(?i)(secret|SECRET|secretKey|SECRET_KEY|SecretKey|SECRET_KEY)[\s=:]["']?[\w-]+["']?'''
tags = ["key", "secret"]

[[rules]]
description = "Slack Token"
regex = '''xox[baprs]-([0-9a-zA-Z]{10,48})?'''
tags = ["key", "slack"]

[[rules]]
description = "Stripe API Key"
regex = '''(?i)(sk_live|pk_live|rk_live)_([0-9a-zA-Z]{24,})?'''
tags = ["key", "stripe"]

[[rules]]
description = "GitHub Token"
regex = '''(?i)(github|GH|gh)[\s=:]["']?ghp_[0-9a-zA-Z]{36}["']?'''
tags = ["key", "github"]

[[rules]]
description = "Google API Key"
regex = '''(?i)(AIza[0-9A-Za-z-_]{35})'''
tags = ["key", "google"]

[[rules]]
description = "Heroku API Key"
regex = '''(?i)(heroku)[\s=:]["']?[0-9a-fA-F]{32}["']?'''
tags = ["key", "heroku"]

[[rules]]
description = "Twilio API Key"
regex = '''(?i)(twilio)[\s=:]["']?([a-zA-Z0-9]{34})["']?'''
tags = ["key", "twilio"]

[allowlist]
files = [
    "README.md",
    "docs/"
]

patterns = [
    "dummy_key",
    "example_key"
]

[log]
level = "info"
path = "gitleaks.log"
